### ISSUE TITLE
Lots of "failed request (code: 504)" "failed request (code: 500)" and "failed request (code: RequestError: socket hang up)"

### ISSUE THREAD

**Issue by texastoastt** [SpaceK33z/plex2netflix#28]
Only a small fraction of my library is getting scanned. Getting loads of the following errors codes below (with log snippets):

Resident Evil: The Final Chapter (2016) - failed request (code: 500)
Waynes World (1992) - failed request (code: RequestError: socket hang up)
Rings (2017) - failed request (code: 500)
Silver Linings Playbook (2012) - failed request (code: RequestError: socket hang up)
Tremors 5: Bloodlines (2015) - failed request (code: RequestError: socket hang up)
Signs (2002) - failed request (code: RequestError: socket hang up)
Predator (1987) - failed request (code: 500)
The Secret Life of Pets (2016) - failed request (code: 500)
Spotlight (2015) - failed request (code: RequestError: socket hang up)
The Fox and the Hound (1981) - failed request (code: RequestError: socket hang up)
Passengers (2016) - failed request (code: 500)

Four Christmases (2008) - failed request (code: 504)
X-Men Origins: Wolverine (2009) - failed request (code: 504)
From Paris with Love (2010) - failed request (code: 504)
Welcome to the Rileys (2010) - failed request (code: 504)
The Mummy (1999) - failed request (code: 504)
The Sorcerers Apprentice (2010) - failed request (code: 504)
Theres Something About Mary (1998) - failed request (code: 504)
Shes Out of My League (2010) - failed request (code: 504)
Split (2016) - failed request (code: 504)

This is just a small collection, as i am getting hundreds of these responses. 

NPM is version: 5.3.0
plex2netflix version: 0.5.1

**Comment by SpaceK33z** [comment]
Thanks for your bug report. It seems that the API provider I'm using, uNoGs, is having some issues. I will contact them and see if it is possible to fix.

**Comment by SpaceK33z** [comment]
I got a quick answer and it's fixed now :)!

**Comment by texastoastt** [comment]
Unfortunately, it look like I'm still having the same issue. Though, now, it also crashes plexmediaserver in the process. 

Searching in Documentaries.
-------
Macheads (2009) - failed request (code: 504)
Loose Change 9/11: An American Coup (2009) - failed request (code: 504)
Before the Flood (2016) - failed request (code: 504)
Loose Change: Final Cut (2007) - failed request (code: 504)
Hallelujah (1929) - failed request (code: 504)
Helvetica (2007) - failed request (code: 504)
Sunday Driver (2005) - failed request (code: 504)
We Are Blood (2015) - failed request (code: 504)
Steve-O: Demise and Rise (2009) - failed request (code: 504)
-------
Searching in Movies.
-------
TypeError: Cannot read property 'title' of undefined

**Comment by SpaceK33z** [comment]
That is interesting, perhaps my own proxy server fails for some reason.

**Comment by texastoastt** [comment]
Anything i can do to help? Is there a verbose or debug option i can output for you?

**Comment by seanvree** [comment]
Has this been resolved by chance?

**Comment by SpaceK33z** [comment]
For me it works (at least when I tested this a month ago), doesn't it for you?

**Comment by SpaceK33z** [comment]
Maybe I can spend some time on this soon, I've been quite busy.

**Comment by seanvree** [comment]
@SpaceK33z  - 

Nope, something is def not working right. 

Love the project! Would love to see this bug worked out!

![image](https://user-images.githubusercontent.com/8906637/30515055-229a45bc-9ad6-11e7-86a4-b34f4c0285cf.png)

**Comment by texastoastt** [comment]
Just circling back, and this still seems to be a problem. Any ideas/updates?

**Comment by deathbybandaid** [comment]
Drats,,, I used this forever ago, and went to run it this morning to find it doesn't work anymore.

**Comment by texastoastt** [comment]
Looks like this is still a problem. Worse, even. Basically get nothing but Error 500's now.

**Comment by benrowe** [comment]
@SpaceK33z could you provide a very brief overview of where this bug is happening? I'd like to see if I can fix it.

**Comment by texastoastt** [comment]
It happens as soon as i run the command. Here's the syntax, from command execution til i canceled the run:

```
~]# plex2netflix --token=***************
Successfully connected to Plex.
-------
Searching in Movies.
-------
The Empire Strikes Back (1980) - failed request (code: 500)
Elysium (2013) - failed request (code: 500)
Elle (2016) - failed request (code: 500)
Evil Dead II (1987) - failed request (code: 500)
Entourage (2015) - failed request (code: 500)
Extreme Movie (2008) - failed request (code: 500)
Factory Girl (2006) - failed request (code: 500)
Edward Scissorhands (1990) - failed request (code: 500)
Edge of Tomorrow (2014) - failed request (code: 500)
End of Watch (2012) - failed request (code: 500)
Braveheart (1995) - failed request (code: 500)
Friday the 13th (2009) - failed request (code: 500)
Final Destination 2 (2003) - failed request (code: 500)
The Faculty (1998) - failed request (code: 500)
Fast & Furious (2009) - failed request (code: 500)
Ex Machina (2015) - failed request (code: 500)
Fire in the Sky (1993) - failed request (code: 500)
Fast Five (2011) - failed request (code: 500)
First Sunday (2008) - failed request (code: 500)
Experimenter (2015) - failed request (code: 500)
Flight 93 (2006) - failed request (code: 500)
Forgetting Sarah Marshall (2008) - failed request (code: 500)
The Founder (2017) - failed request (code: 500)
Four Christmases (2008) - failed request (code: 500)
Fast & Furious 6 (2013) - failed request (code: 500)
Funny People (2009) - failed request (code: 500)
Get Out (2017) - failed request (code: 500)
Ginger Snaps (2001) - failed request (code: 500)
The Girl Next Door (2004) - failed request (code: 500)
9 (2009) - yes
The Amityville Horror (2005) - nope
American Pie (1999) - nope
American History X (1998) - nope
Summer of Sam (1999) - failed request (code: 500)
Austin Powers: The Spy Who Shagged Me (1999) - nope
Surrogates (2009) - failed request (code: 500)
Tickled (2016) - failed request (code: 500)
What We Do in the Shadows (2014) - failed request (code: 500)
28 Weeks Later (2007) - failed request (code: 500)
Austin Powers in Goldmember (2002) - nope
Zodiac (2007) - failed request (code: 500)
Fantastic Beasts and Where to Find Them (2016) - failed request (code: 500)
Friday the 13th Part 2 (1981) - failed request (code: 500)
コクリコ坂から (2012) - failed request (code: 500)
Halloween III: Season of the Witch (1982) - failed request (code: 500)
Goon: Last of the Enforcers (2017) - failed request (code: 500)
Good Luck Chuck (2007) - failed request (code: 500)
Harry Potter and the Philosophers Stone (2001) - failed request (code: 500)
Beetlejuice (1988) - nope
Moana (2016) - failed request (code: 500)
The Proposal (2009) - failed request (code: 500)
The Butterfly Effect (2004) - nope
Wild Wild West (1999) - failed request (code: 500)
Zootopia (2016) - failed request (code: 500)
Tangled (2010) - failed request (code: 500)
Sunday Driver (2005) - nope
^C
```

**Comment by SpaceK33z** [comment]
Fix should be released in `plex2netflix@0.5.4`, let me know if it doesn't work for you.

Sorry @benrowe, didn't see your message.

It had to do with this package firing many many requests to the Plex server at once (for every movie or show it needs to do a separate request), since this was not batched it could crash the Plex server. Anyway, now it performs maximum 30 requests concurrently.
